expr = '-1/RM (-((4 R DiracDelta[t-tprime-2 xtilde^2-2 e^2 Sin[\[Theta]tilde]^2])/((R+t-tprime) (R-t+tprime)))+(4 R (-t+tprime) HeavisideTheta[t-tprime-2 xtilde^2-2 e^2 Sin[\[Theta]tilde]^2])/((R+t-tprime)^2 (R-t+tprime)^2)-Log[1-(2 R)/(R-t+tprime)] (DiracDelta^\[Prime])[t-tprime-2 xtilde^2-2 e^2 Sin[\[Theta]tilde]^2]+Log[1-(2 R)/(R-2 xtilde^2-2 e^2 Sin[\[Theta]tilde]^2)] (DiracDelta^\[Prime])[t-tprime-2 xtilde^2-2 e^2 Sin[\[Theta]tilde]^2])'

while '  ' in expr:
    expr = expr.replace('  ', ' ')

expr = expr.replace('HeavisideTheta[-\[Tau]1+\[Tau]2]', '1')
expr = expr.replace('HeavisideTheta[\[Tau]1-\[Tau]2]', '0')
expr = expr.replace('\[Tau]1', 'tau1')
expr = expr.replace('\[Tau]2', 'tau2')
expr = expr.replace(' ', ' * ')
expr = expr.replace('+', ' + ')
expr = expr.replace('-', ' - ')
expr = expr.replace('/', ' / ')
expr = expr.replace('^', '**')
expr = expr.replace('Sqrt', 'np.sqrt')
expr = expr.replace('Exp', 'np.exp')
expr = expr.replace('Cos', 'np.cos')
expr = expr.replace('Sin', 'np.sin')
expr = expr.replace('[', '(')
expr = expr.replace(']', ')')

expr = expr.replace('HeavisideTheta', 'np.heaviside')
expr = expr.replace('Abs', 'np.abs')
expr = expr.replace('DiracDelta(', 'dirac_delta(t, ')
expr = expr.replace('\(Pi)', 'np.pi')
expr = expr.replace('\(Omega)', 'omega')
expr = expr.replace('omega2', 'omega * 2')
expr = expr.replace('\(Rho)', 'rho')
expr = expr.replace('\(Tau)', 'tau')
expr = expr.replace('\(Xi)', 'xi')
expr = expr.replace('Log', 'np.log')
expr = expr.replace('(DiracDelta**\(Prime))', 'dirac_delta_prime')
expr = expr.replace(')(', ') * (')
for i in range(10):
    expr = expr.replace(f'{i}(', f'{i} * (')    
    expr = expr.replace(f'){i}', f') * {i}')
expr = expr.replace(')t', ') * t')
expr = expr.replace('E**', 'np.exp')
print(expr)